<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class ActionMatrixSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            //RECOMMENDED Actions
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => null,
                'action_two_by_role' => null,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 4,
            ],
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 7,
            ],
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => 'REJECT_APP',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 7,
            ],
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => 'FOR_TO_DEP',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveToSelectedDepartment',
                'sent_to_role' => null,
            ],
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 10,
                'action_two' => null,
                'action_two_by_role' => null,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 4,
            ],
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 10,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 4,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 4,
                'action_two' => null,
                'action_two_by_role' => null,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 10,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 7,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 10,
            ],
            //OBJECT Actions
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 7,
                'action_two' => null,
                'action_two_by_role' => null,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 7,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'openApplication',
                'sent_to_role' => 6,
            ],
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 7,
                'action_two' => 'REJECT_APP',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'disposeTheApplication',
                'sent_to_role' => null,
            ],
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 4,
                'action_two' => null,
                'action_two_by_role' => null,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 4,
                'action_two' => 'REJECT_APP',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 7,
            ],
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 10,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 7,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 10,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 7,
                'action_to_be_taken' => 'openApplication',
                'sent_to_role' => 6,
            ],
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 4,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 4,
            ],
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 4,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'openApplication',
                'sent_to_role' => 6,
            ],
            //UNHOLD Actions
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'UNHOLD',
                'action_one_by_role' => 4,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 4,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'UNHOLD',
                'action_one_by_role' => 4,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 4,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            //APPROVE actions
            [
                'service_type' => 'SUB_MUT',
                'action_one' => 'APPROVE',
                'action_one_by_role' => 10,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 4,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 10,
            ],

            //Deed Of Apartment Action Matrix - Lalit Tiwari (19/Nov/2024)
            // 7 - section officer, 10 - Deputy L&DO, 11 - L&DO , applicant - 6
            [
                'service_type' => 'DOA',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => null,
                'action_two_by_role' => null,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 11,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 7,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => 'REJECT_APP',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'disposeTheApplication',
                'sent_to_role' => null,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => 'FOR_TO_DEP',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveToSelectedDepartment',
                'sent_to_role' => null,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 7,
                'action_two' => null,
                'action_two_by_role' => null,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 7,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'openApplication',
                'sent_to_role' => 6,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 10,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 7,
                'action_to_be_taken' => 'openApplication',
                'sent_to_role' => 6,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 7,
                'action_two' => 'REJECT_APP',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'disposeTheApplication',
                'sent_to_role' => null,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 10,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 11,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 10,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 7,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 10,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 11,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'REC_FOR_APR',
                'action_one_by_role' => 10,
                'action_two' => null,
                'action_two_by_role' => null,
                'action_to_be_taken' => 'generateDeedOfApartmentLetter',
                'sent_to_role' => null,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 10,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 11,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 11,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'openApplication',
                'sent_to_role' => 6,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 11,
                'action_two' => 'PROOFREADINGLINK',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 7,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 11,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 11,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 11,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'openApplication',
                'sent_to_role' => 6,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'PROOFREADINGLINK',
                'action_one_by_role' => 10,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 7,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 7,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 11,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'UNHOLD',
                'action_one_by_role' => 7,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 7,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'UNHOLD',
                'action_one_by_role' => 7,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 7,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'PROOFREADINGLINK',
                'action_one_by_role' => 10,
                // 'action_two' => 'RECOMMENDED',
                'action_two' => 'RECOMMENDED_FOR_APPROVAL',
                'action_two_by_role' => 7,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'HOLD',
                'action_one_by_role' => 7,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 7,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'HOLD',
                'action_one_by_role' => 7,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 7,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'UNHOLD',
                'action_one_by_role' => 7,
                'action_two' => 'RECOMMENDED_FOR_APPROVAL',
                'action_two_by_role' => 7,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'DOA',
                'action_one' => 'HOLD',
                'action_one_by_role' => 7,
                'action_two' => 'RECOMMENDED_FOR_APPROVAL',
                'action_two_by_role' => 7,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],


            // /** Conversion actions -- added by Nitin on 25-11-2024*/
            // [
            //     'service_type' => 'CONVERSION',
            //     'action_one' => 'RECOMMENDED',
            //     'action_one_by_role' => 7,
            //     'action_two' => null,
            //     'action_two_by_role' => null,
            //     'action_to_be_taken' => 'moveForward',
            //     'sent_to_role' => 10,
            // ],
            // [
            //     'service_type' => 'CONVERSION',
            //     'action_one' => 'RECOMMENDED',
            //     'action_one_by_role' => 7,
            //     'action_two' => 'RECOMMENDED',
            //     'action_two_by_role' => 10,
            //     'action_to_be_taken' => 'moveForward',
            //     'sent_to_role' => 4,
            // ],
            // [
            //     'service_type' => 'CONVERSION',
            //     'action_one' => 'RECOMMENDED',
            //     'action_one_by_role' => 7,
            //     'action_two' => 'OBJECT',
            //     'action_two_by_role' => 10,
            //     'action_to_be_taken' => 'moveBack',
            //     'sent_to_role' => 7,
            // ],
            // [
            //     'service_type' => 'CONVERSION',
            //     'action_one' => 'RECOMMENDED',
            //     'action_one_by_role' => 7,
            //     'action_two' => 'REJECT_APP',
            //     'action_two_by_role' => 10,
            //     'action_to_be_taken' => 'moveBack',
            //     'sent_to_role' => 7,
            // ],
            // [
            //     'service_type' => 'CONVERSION',
            //     'action_one' => 'RECOMMENDED',
            //     'action_one_by_role' => 7,
            //     'action_two' => 'FOR_TO_DEP',
            //     'action_two_by_role' => 10,
            //     'action_to_be_taken' => 'moveToSelectedDepartment',
            //     'sent_to_role' => null,
            // ],
            // [
            //     'service_type' => 'CONVERSION',
            //     'action_one' => 'OBJECT',
            //     'action_one_by_role' => 7,
            //     'action_two' => null,
            //     'action_two_by_role' => null,
            //     'action_to_be_taken' => 'moveForward',
            //     'sent_to_role' => 10,
            // ],
            // [
            //     'service_type' => 'CONVERSION',
            //     'action_one' => 'OBJECT',
            //     'action_one_by_role' => 7,
            //     'action_two' => 'OBJECT',
            //     'action_two_by_role' => 10,
            //     'action_to_be_taken' => 'openApplication',
            //     'sent_to_role' => 6,
            // ],
            // [
            //     'service_type' => 'CONVERSION',
            //     'action_one' => 'OBJECT',
            //     'action_one_by_role' => 7,
            //     'action_two' => 'REJECT_APP',
            //     'action_two_by_role' => 10,
            //     'action_to_be_taken' => 'disposeTheApplication',
            //     'sent_to_role' => null,
            // ],
            // [
            //     'service_type' => 'CONVERSION',
            //     'action_one' => 'APPROVE',
            //     'action_one_by_role' => 10,
            //     'action_two' => null,
            //     'action_two_by_role' => null,
            //     'action_to_be_taken' => 'moveForward',
            //     'sent_to_role' => 4,
            // ],
            // [
            //     'service_type' => 'CONVERSION',
            //     'action_one' => 'APPROVE',
            //     'action_one_by_role' => 10,
            //     'action_two' => 'RECOMMENDED',
            //     'action_two_by_role' => 4,
            //     'action_to_be_taken' => 'sendProofReadingInvitationLink',
            //     'sent_to_role' => 6,
            // ],
            // [
            //     'service_type' => 'CONVERSION',
            //     'action_one' => 'APPROVE',
            //     'action_one_by_role' => 10,
            //     'action_two' => 'OBJECT',
            //     'action_two_by_role' => 4,
            //     'action_to_be_taken' => 'moveBack',
            //     'sent_to_role' => 10,
            // ],
            // [
            //     'service_type' => 'CONVERSION',
            //     'action_one' => 'REC_FOR_APR',
            //     'action_one_by_role' => 4,
            //     'action_two' => null,
            //     'action_two_by_role' => null,
            //     'action_to_be_taken' => 'generateMutationLetter',
            //     'sent_to_role' => 10,
            // ],
            // [
            //     'service_type' => 'CONVERSION',
            //     'action_one' => 'HOLD',
            //     'action_one_by_role' => 4,
            //     'action_two' => null,
            //     'action_two_by_role' => null,
            //     'action_to_be_taken' => 'hold',
            //     'sent_to_role' => 4,
            // ],
            // [
            //     'service_type' => 'CONVERSION',
            //     'action_one' => 'HOLD',
            //     'action_one_by_role' => 4,
            //     'action_two' => 'RECOMMENDED',
            //     'action_two_by_role' => 4,
            //     'action_to_be_taken' => 'moveBack',
            //     'sent_to_role' => 10,
            // ],
            // [
            //     'service_type' => 'CONVERSION',
            //     'action_one' => 'HOLD',
            //     'action_one_by_role' => 4,
            //     'action_two' => 'OBJECT',
            //     'action_two_by_role' => 4,
            //     'action_to_be_taken' => 'moveBack',
            //     'sent_to_role' => 10,
            // ],



            // Conversion actions - SOURAV CHAUHAN (09/Dec/2024)
            //RECOMMENDED Actions
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => null,
                'action_two_by_role' => null,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 4,
            ],
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 7,
            ],
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => 'REJECT_APP',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 7,
            ],
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => 'FOR_TO_DEP',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveToSelectedDepartment',
                'sent_to_role' => null,
            ],
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 10,
                'action_two' => null,
                'action_two_by_role' => null,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 4,
            ],
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 10,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 4,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 4,
                'action_two' => null,
                'action_two_by_role' => null,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 10,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 7,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 10,
            ],
            //OBJECT Actions
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 7,
                'action_two' => null,
                'action_two_by_role' => null,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 7,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'openApplication',
                'sent_to_role' => 6,
            ],
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 7,
                'action_two' => 'REJECT_APP',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'disposeTheApplication',
                'sent_to_role' => null,
            ],
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 4,
                'action_two' => null,
                'action_two_by_role' => null,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 4,
                'action_two' => 'REJECT_APP',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 7,
            ],
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 10,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 7,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 10,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 7,
                'action_to_be_taken' => 'openApplication',
                'sent_to_role' => 6,
            ],
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 4,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 4,
            ],
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 4,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'openApplication',
                'sent_to_role' => 6,
            ],
            //UNHOLD Actions
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'UNHOLD',
                'action_one_by_role' => 4,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 4,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'UNHOLD',
                'action_one_by_role' => 4,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 4,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            //APPROVE actions
            [
                'service_type' => 'CONVERSION',
                'action_one' => 'APPROVE',
                'action_one_by_role' => 10,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 4,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 10,
            ],




            /** LUC actions -  added by Nitin - 02-12-2024 */
            [
                'service_type' => 'LUC',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => null,
                'action_two_by_role' => null,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'LUC',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 11,
            ],
            [
                'service_type' => 'LUC',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 7,
            ],
            [
                'service_type' => 'LUC',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => 'REJECT_APP',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'disposeTheApplication',
                'sent_to_role' => null,
            ],
            [
                'service_type' => 'LUC',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => 'FOR_TO_DEP',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveToSelectedDepartment',
                'sent_to_role' => null,
            ],
            [
                'service_type' => 'LUC',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 7,
                'action_two' => null,
                'action_two_by_role' => null,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'LUC',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 7,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'disposeTheApplication',
                'sent_to_role' => null,
            ],
            [
                'service_type' => 'LUC',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 7,
                'action_two' => 'REJECT_APP',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'openApplication',
                'sent_to_role' => 6,
            ],
            [
                'service_type' => 'LUC',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 10,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 11,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'LUC',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 11,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'openApplication',
                'sent_to_role' => 6,
            ],
            [
                'service_type' => 'LUC',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 10,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 7,
                'action_to_be_taken' => 'openApplication',
                'sent_to_role' => 6,
            ],
            [
                'service_type' => 'LUC',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 10,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 11,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'LUC',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 11,
                'action_two' => 'APPROVE',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => null,
            ],
            // [
            //     'service_type' => 'CONVERSION',
            //     'action_one' => 'OBJECT',
            //     'action_one_by_role' => 10,
            //     'action_two' => 'OBJECT',
            //     'action_two_by_role' => 7,
            //     'action_to_be_taken' => 'openApplication',
            //     'sent_to_role' => 6,
            // ],

            // Action Matrixes for NOC Application - Lalit Tiwari (21/March/2025) 
            // 7 - section officer, 10 - Deputy L&DO, applicant - 6
            [
                'service_type' => 'NOC',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => null,
                'action_two_by_role' => null,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'NOC',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 7,
            ],
            [
                'service_type' => 'NOC',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => 'REJECT_APP',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'disposeTheApplication',
                'sent_to_role' => null,
            ],
            [
                'service_type' => 'NOC',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => 'FOR_TO_DEP',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveToSelectedDepartment',
                'sent_to_role' => null,
            ],
            [
                'service_type' => 'NOC',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 7,
                'action_two' => null,
                'action_two_by_role' => null,
                'action_to_be_taken' => 'moveForward',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'NOC',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 7,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'openApplication',
                'sent_to_role' => 6,
            ],
            [
                'service_type' => 'NOC',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 10,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 7,
                'action_to_be_taken' => 'openApplication',
                'sent_to_role' => 6,
            ],
            [
                'service_type' => 'NOC',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 7,
                'action_two' => 'REJECT_APP',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'disposeTheApplication',
                'sent_to_role' => null,
            ],
            [
                'service_type' => 'NOC',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 10,
                'action_two' => 'RECOMMENDED',
                'action_two_by_role' => 7,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 10,
            ],
            [
                'service_type' => 'NOC',
                'action_one' => 'REC_FOR_APR',
                'action_one_by_role' => 10,
                'action_two' => null,
                'action_two_by_role' => null,
                'action_to_be_taken' => 'generateNocLetter',
                'sent_to_role' => null,
            ],
            [
                'service_type' => 'NOC',
                'action_one' => 'RECOMMENDED',
                'action_one_by_role' => 7,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 10,
                'action_to_be_taken' => 'moveBack',
                'sent_to_role' => 7,
            ],
            [
                'service_type' => 'NOC',
                'action_one' => 'OBJECT',
                'action_one_by_role' => 10,
                'action_two' => 'OBJECT',
                'action_two_by_role' => 7,
                'action_to_be_taken' => 'openApplication',
                'sent_to_role' => 6,
            ],
        ];

        foreach ($items as $item) {
            DB::table('action_matrixes')->updateOrInsert(
                [
                    'service_type' => $item['service_type'],
                    'action_one' =>  $item['action_one'],
                    'action_one_by_role' =>  $item['action_one_by_role'],
                    'action_two' =>  $item['action_two'],
                    'action_two_by_role' =>  $item['action_two_by_role'],
                ],
                [
                    'action_to_be_taken' =>  $item['action_to_be_taken'],
                    'sent_to_role' =>  $item['sent_to_role'],
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ]
            );
        }
    }
}